export const courts = {
  data: [
    {
      id: 1,
      name: "Estadio La Cancha 1",
      sport: "Fútbol",
      city: "Bogotá",
      status: "Activo",
      description: "Estadio La Cancha 1",
      capacity: 7,
      pricePerHour: 4500.0,
      address: "calle 34 2",
      neighborhood: "Tunal",
      imageUrl: [
        "https://i.imgur.com/4w8mYnz.jpeg",
        "https://i.imgur.com/61nWS9L.jpeg",
        "https://i.imgur.com/7Q2BQK7.jpeg",
        "https://i.imgur.com/8WZl4lb.jpeg",
        "https://i.imgur.com/a8IXPd3.jpeg",
        "https://i.imgur.com/adciAlf.jpeg",
      ],
      features: [
        "Parking disponible",
        "Equipamiento para alquilar",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 2,
      name: "Estadio La Cancha 2",
      sport: "Fútbol",
      city: "Bogotá",
      status: "Activo",
      description: "Estadio La Cancha 2",
      capacity: 7,
      pricePerHour: 3400.0,
      address: "calle 34 2",
      neighborhood: "Tunal",
      imageUrl: [
        "https://i.imgur.com/B0ZledY.jpeg",
        "https://i.imgur.com/BzlUK4d.jpeg",
        "https://i.imgur.com/c0Uq7HC.jpeg",
        "https://i.imgur.com/COVuKDI.jpeg",
        "https://i.imgur.com/cwMubCz.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 3,
      name: "Cancha de Fútbol 3",
      sport: "Fútbol",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/DlvPosz.jpeg",
        "https://i.imgur.com/dnf8V6O.jpeg",
        "https://i.imgur.com/eSGOBOI.jpeg",
        "https://i.imgur.com/fpLnAwb.jpeg",
        "https://i.imgur.com/HhXC2U0.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 4,
      name: "Cancha de Fútbol 4",
      sport: "Fútbol",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/hKvIg3u.jpeg",
        "https://i.imgur.com/HV0O7oZ.jpeg",
        "https://i.imgur.com/HyyNpwh.jpeg",
        "https://i.imgur.com/I6GIlVv.jpeg",
        "https://i.imgur.com/jcJmebJ.jpeg",
        "https://i.imgur.com/jiuqVlw.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
      ],
    },
    {
      id: 5,
      name: "Cancha de Fútbol 5",
      sport: "Fútbol",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/jJfIfgu.jpeg",
        "https://i.imgur.com/kxQxjdl.jpeg",
        "https://i.imgur.com/ky8QfKr.jpeg",
        "https://i.imgur.com/le5EEK2.jpeg",
        "https://i.imgur.com/MD1ImVs.jpeg",
      ],
      features: [
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 6,
      name: "Cancha de Basket 1",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/HhXC2U0.jpeg",
        "https://i.imgur.com/NMxtRYP.jpeg",
        "https://i.imgur.com/SlbEC4b.jpeg",
        "https://i.imgur.com/tMcTUo1.jpeg",
        "https://i.imgur.com/yvRyGcg.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
      ],
    },
    {
      id: 7,
      name: "Cancha de Basket 2",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/hKvIg3u.jpeg",
        "https://i.imgur.com/HV0O7oZ.jpeg",
        "https://i.imgur.com/HyyNpwh.jpeg",
        "https://i.imgur.com/I6GIlVv.jpeg",
        "https://i.imgur.com/jcJmebJ.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 8,
      name: "Cancha de Basket 3",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/jiuqVlw.jpeg",
        "https://i.imgur.com/jJfIfgu.jpeg",
        "https://i.imgur.com/kxQxjdl.jpeg",
        "https://i.imgur.com/ky8QfKr.jpeg",
        "https://i.imgur.com/le5EEK2.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 9,
      name: "Cancha de Basket 4",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/MD1ImVs.jpeg",
        "https://i.imgur.com/NMxtRYP.jpeg",
        "https://i.imgur.com/SlbEC4b.jpeg",
        "https://i.imgur.com/tMcTUo1.jpeg",
        "https://i.imgur.com/yvRyGcg.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 10,
      name: "Cancha de Basket 5",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/HV0O7oZ.jpeg",
        "https://i.imgur.com/HyyNpwh.jpeg",
        "https://i.imgur.com/I6GIlVv.jpeg",
        "https://i.imgur.com/jcJmebJ.jpeg",
        "https://i.imgur.com/jiuqVlw.jpeg",
        "https://i.imgur.com/jJfIfgu.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 11,
      name: "Cancha de Basket 5",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/HV0O7oZ.jpeg",
        "https://i.imgur.com/HyyNpwh.jpeg",
        "https://i.imgur.com/I6GIlVv.jpeg",
        "https://i.imgur.com/jcJmebJ.jpeg",
        "https://i.imgur.com/jiuqVlw.jpeg",
        "https://i.imgur.com/jJfIfgu.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 12,
      name: "Cancha de Basket 5",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/HV0O7oZ.jpeg",
        "https://i.imgur.com/HyyNpwh.jpeg",
        "https://i.imgur.com/I6GIlVv.jpeg",
        "https://i.imgur.com/jcJmebJ.jpeg",
        "https://i.imgur.com/jiuqVlw.jpeg",
        "https://i.imgur.com/jJfIfgu.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 13,
      name: "Cancha de Basket 5",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/HV0O7oZ.jpeg",
        "https://i.imgur.com/HyyNpwh.jpeg",
        "https://i.imgur.com/I6GIlVv.jpeg",
        "https://i.imgur.com/jcJmebJ.jpeg",
        "https://i.imgur.com/jiuqVlw.jpeg",
        "https://i.imgur.com/jJfIfgu.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
    {
      id: 14,
      name: "Cancha de Basket 5",
      sport: "Baloncesto",
      city: "Buenos Aires",
      status: "Activo",
      description: "Cancha techada con césped sintético",
      capacity: 10,
      pricePerHour: 150.0,
      address: "Calle 123, Bogotá",
      neighborhood: "Centro",
      imageUrl: [
        "https://i.imgur.com/HV0O7oZ.jpeg",
        "https://i.imgur.com/HyyNpwh.jpeg",
        "https://i.imgur.com/I6GIlVv.jpeg",
        "https://i.imgur.com/jcJmebJ.jpeg",
        "https://i.imgur.com/jiuqVlw.jpeg",
        "https://i.imgur.com/jJfIfgu.jpeg",
      ],
      features: [
        "Parking disponible",
        "Estadio abierto",
        "Equipamiento para alquilar",
        "Pet friendly",
        "Accesible",
      ],
      featuresImageUrl: [
        "https://i.imgur.com/B87sLqx.png",
        "https://i.imgur.com/f8AWiAe.png",
        "https://i.imgur.com/RbTLOlC.png",
        "https://i.imgur.com/vhT9hqg.png",
        "https://i.imgur.com/vQBaE9p.png",
      ],
    },
  ],
  currentPage: 1,
  pageSize: 10,
  totalElements: 14,
  totalPages: 2,
  hasNextPage: true,
  hasPrevPage: false,
};
