export const courts = [
  {
    id: 1,
    name: "Estadio La Cancha 1",
    sport: "Fútbol",
    city: "Bogotá",
    status: "Activo",
    description: "Estadio La Cancha 1",
    capacity: 7,
    pricePerHour: 4500,
    address: "calle 34 2",
    neighborhood: "Tunal",
    properties: [
      "Mantenimiento diario",
      "Insumos de la mejor calidad",
      "Profesionales de más alto nivel",
    ],
    imageUrl: [
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
    ],
  },
  {
    id: 2,
    name: "Estadio La Cancha 2",
    sport: "Fútbol",
    city: "Bogotá",
    status: "Activo",
    description: "Estadio La Cancha 2",
    capacity: 7,
    pricePerHour: 3400,
    address: "calle 34 2",
    neighborhood: "Tunal",
    properties: [
      "Mantenimiento diario",
      "Insumos de la mejor calidad",
      "Profesionales de más alto nivel",
    ],
    imageUrl: [
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
    ],
  },
  {
    id: 3,
    name: "Cancha de Fútbol 3",
    sport: "Fútbol",
    city: "Buenos Aires",
    status: "Activo",
    description: "Cancha techada con césped sintético",
    capacity: 10,
    pricePerHour: 150,
    address: "Calle 123, Bogotá",
    neighborhood: "Centro",
    properties: [
      "Mantenimiento diario",
      "Insumos de la mejor calidad",
      "Profesionales de más alto nivel",
    ],
    imageUrl: [
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
    ],
  },
  {
    id: 4,
    name: "Cancha de Fútbol 4",
    sport: "Fútbol",
    city: "Buenos Aires",
    status: "Activo",
    description: "Cancha techada con césped sintético",
    capacity: 10,
    pricePerHour: 150,
    address: "Calle 123, Bogotá",
    neighborhood: "Centro",
    properties: [
      "Mantenimiento diario",
      "Insumos de la mejor calidad",
      "Profesionales de más alto nivel",
    ],
    imageUrl: [
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
      "../../public/images/detail/detail.jpeg",
    ],
  },
  // {
  //   id: 5,
  //   name: "Cancha de Fútbol 5",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 6,
  //   name: "Cancha de Basket 1",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 7,
  //   name: "Cancha de Basket 2",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 8,
  //   name: "Cancha de Basket 3",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 9,
  //   name: "Cancha de Basket 4",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 10,
  //   name: "Cancha de Basket 5",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 11,
  //   name: "Cancha Central de Tenis 1",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 12,
  //   name: "Cancha Central de Tenis 2",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 13,
  //   name: "Cancha Central de Tenis 3",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
  // {
  //   id: 14,
  //   name: "Cancha Central de Tenis 4",
  //   sport: "Fútbol",
  //   city: "Buenos Aires",
  //   status: "Activo",
  //   description: "Cancha techada con césped sintético",
  //   capacity: 10,
  //   pricePerHour: 150,
  //   address: "Calle 123, Bogotá",
  //   neighborhood: "Centro",
  //   imageUrl: [
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //     "../../public/images/detail/detail.jpeg",
  //   ],
  // },
];
